CREATE ROLE constellation WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'constellation';

CREATE DATABASE constellation
  WITH
  OWNER = constellation
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
